server:
  port: 8090

spring:
  application:
    name: microservice-iam
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iam_db
    username: root
    password: Karlam030879@
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8888

authorization:
  jwt:
    secret: AylluCare2024SecretKeyForJWTSigningMustBeAtLeast256BitsLongForHS256Algorithm
    expiration:
      days: 7

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/